/// Flutter icons BoatIcons
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BoatIcons
///      fonts:
///       - asset: fonts/BoatIcons.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

class BoatIcons {
  BoatIcons._();

  static const _kFontFam = 'BoatIcons';
  static const String? _kFontPkg = null;

  static const IconData boaticon = IconData(
    0xe801,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData addboat = IconData(
    0xe802,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
}
