/// Flutter icons TrailIcon
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TrailIcon
///      fonts:
///       - asset: fonts/TrailIcon.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

class TrailIcon {
  TrailIcon._();

  static const _kFontFam = 'TrailIcon';
  static const String? _kFontPkg = null;

  static const IconData trailicon = IconData(
    0xe803,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
}
